site_name: 图灵 2024 学长组资料汇总
site_url: https://turing2024.tonycrane.cc/
site_description: 图灵 2024 学长组信息汇总
repo_name: TuringDoneRight
repo_url: https://github.com/ZJU-Turing/TuringDoneRight/
edit_uri: tree/master/docs
copyright: Copyright &copy; 2023-2024 浙江大学图灵班学长组

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  favicon: images/icon.png
  features:
    - content.code.annotate
    - navigation.tracking
    # - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.suggest
  font: false
  palette:
    - scheme: default

extra:
  analytics:
    provider: custom
    property: G-G594CHT348

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://cdn.tonycrane.cc/turing2022/css/tasklist.css
  - https://cdn.tonycrane.cc/turing2022/css/card.css
  # - https://cdn.tonycrane.cc/turing2022/css/custom.css
  - css/custom.css

extra_javascript:
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - https://cdn.tonycrane.cc/turing2022/js/katex.js
  - https://pan.yusux.xyz/source_one/js/suspension_img/suspension.js
  # js/toc.js    # this is in template 'base.html'
  # js/scheme.js # this is in template 'base.html'

plugins:
  - search
  - heti:
      extra_skipped_class:
        - arithmatex
  - statistics

nav:
  - 主页: index.md
  - 写在前面的话: preface.md
  - 新生入学流程: checkin.md
  - 学长组 Q&A 总结: qa.md
  - 暑假购机推荐: machine.md
  - 新生防诈骗指南: anti_fraud.md
  - 暑假学习建议: summer_study.md
  - 校网连接指南: rvpn.md
  # - 如何获取信息: getinfo.md
  # - 校园生活指南: living.md
  # - 图灵班选课指南: course_selection.md
  # - 图灵班课程学习建议:
  #   - courses/index.md
  #   - 数学分析（甲）Ⅰ（H）: courses/math_analysis1.md
  #   - 线性代数 Ⅰ（H）: courses/linear_algebra1.md
  #   - 程序设计与算法基础: courses/programming.md
  #   - 中国近现代史纲要（H）: courses/modern_history.md
  #   - 思想道德与法治: courses/morality_law.md
  #   - 形势与政策 Ⅰ: courses/situation_policy.md
  #   - 数学分析（甲）Ⅱ（H）: courses/math_analysis2.md
  #   - 线性代数 Ⅱ（H）: courses/linear_algebra2.md
  #   - 普通物理学 Ⅰ（H）: courses/physics1.md
  #   - 普通物理学实验 Ⅰ: courses/physics_experiment1.md
  #   - 离散数学理论基础: courses/discrete_math.md
  #   - 网络空间安全导论: courses/cyberspace_security.md
  # - 通识选修课经验: general.md
  # - 成为一个合格的 CS 人: cser.md
  # - 社团、学生组织体验反馈: organizations.md
